name: Build and Push Docker Image to Docker Hub

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4 # Use a specific major version

      # Sets up the Docker Buildx builder instance
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Logs into Docker Hub using secrets
      # https://github.com/docker/login-action
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Builds and pushes the Docker image
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Use the current directory as context
          file: ./Dockerfile # Path to the Dockerfile
          push: true # Actually push the image
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/podcast-transcriber:latest # Replace 'podcast-transcriber' if your repo name is different
          # Example of adding another tag with the commit SHA for uniqueness:
          # tags: |
          #  ${{ secrets.DOCKERHUB_USERNAME }}/podcast-transcriber:latest
          #  ${{ secrets.DOCKERHUB_USERNAME }}/podcast-transcriber:${{ github.sha }}
          cache-from: type=gha # Enable GitHub Actions cache for faster builds
          cache-to: type=gha,mode=max